python manage.py loaddata ./genesearch/fixtures/1genes_h_vivo.json
python manage.py loaddata ./genesearch/fixtures/2genes_h_vivo.json
python manage.py loaddata ./genesearch/fixtures/3genes_h_vivo.json
python manage.py loaddata ./genesearch/fixtures/4genes_h_vivo.json
python manage.py loaddata ./genesearch/fixtures/5genes_h_vivo.json
python manage.py loaddata ./genesearch/fixtures/6genes_h_vivo.json
python manage.py loaddata ./genesearch/fixtures/7genes_h_vivo.json
python manage.py loaddata ./genesearch/fixtures/8genes_h_vivo.json
python manage.py loaddata ./genesearch/fixtures/9genes_h_vivo.json