# Generated by Django 2.2.6 on 2019-12-03 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('name', 'species', 'status'),
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('fpkm', models.FloatField()),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genes', to='genesearch.Sample')),
            ],
            options={
                'ordering': ('symbol', 'sample', 'fpkm'),
            },
        ),
    ]
